### ISSUE TITLE
3D touching an icon such as rotation lock should not trigger a change

### ISSUE THREAD

**Issue by michyprima** [ioscreatix/Maize#61]
Title. When 3d touching non-3d-touch-enabled icons such as the rotation lock it gets toggled. Imho this should not happen.

Bug is present all the way up to 1.2.1

**Comment by andrewwiik** [comment]
Fixed

**Comment by michyprima** [comment]
The issue is still present in the pre-release distributed via email.
